version: 1.0.{build}

shallow_clone: true

environment:
  matrix:
  - Lua: luajit 2.0.4
    LuaRocks: luarocks 2.3.0
  - Lua: luajit 2.0.3
    LuaRocks: luarocks 2.3.0

configuration:
  - vs_32
  - mingw

install:
  - PATH %CD%\here\bin;C:\mingw\bin;%PATH%
  - curl --location --silent --fail --max-time 120 --connect-timeout 30 https://raw.githubusercontent.com/mpeterv/hererocks/master/hererocks.py > hererocks.py
  - python hererocks.py here --%Lua% --%LuaRocks% --verbose --target=%Configuration% --no-git-cache

build_script:
  - luarocks make "CFLAGS=/EHsc"

test_script:
  #- lua test.lua
  - lua -v

before_deploy:
  - tar -czf here.tar.gz here

deploy:
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: 5WPBv6dYuUaPrUlD5ouNpEGJIofpyhLl8Lry4lt9T6nGE6my5Z4MLNWC879Wer/s
  artifact: here.tar.gz
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
